---
title: "tfg ordenat"
author: "Martina Perez Perez"
date: "2023-05-31"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(readxl)

data <- read_excel("data.xlsx")


```







```{r}

require(knitr)
require(kableExtra)

variables <- names(data)
clase <- c("Character", "Numeric", "Numeric", "Numeric", "Numeric", 
           "Character", "Character", "Character")
categories <- c("AAIC / ADPD / CEB / ESHGC / IBC / ISFTD / JBG / MICCAI / OHBMC", 
                "2012 / 2013 / 2014 / 2015 / 2016 / 2017 / 2018 / 2019 / 2020 / 2021 / 2022 / 2023", 
                "No categories", "No categories", "No categories", 
                "Internacional / Nacional", "Biomedicina / Bioestadística", "Sí / No" )

x <- cbind(variables, clase, categories)

x %>%
  kable(booktabs = TRUE, format = "latex", col.names = c("Variables", "Classe", "Categories"), 
        caption = "Variables de la base de dades del gènere") %>%
  kable_styling(latex_options = c("striped", "condensed", "scale_down", "HOLD_position"), 
                position = "center", full_width = FALSE)



```





```{r}


library(readxl)

data2 <- read_excel("data2.xlsx")

variables2 <- names(data2)
clase2 <- c("Character", "Numeric", "Character", "Numeric", "Character", "Character", "Character" )
categories2 <- c("AAIC / ADPD / CEB / ESHGC / IBC / ISFTD / JBG / MICCAI / OHBMC", 
                "2012 / 2013 / 2014 / 2015 / 2016 / 2017 / 2018 / 2019 / 2020 / 2021 / 2022 / 2023", 
                "Àfrica / Amèrica del Nord / Amèrica del Sud / Àsia / Europa / Oceania" , 
                "No categories", "Internacional / Nacional", "Biomedicina / Bioestadística", "Sí / No" )

x <- cbind(variables2, clase2, categories2)

x %>%
  kable(booktabs = TRUE, format = "latex", col.names = c("Variables", "Classe", "Categories"), 
        caption = "Variables de la base de dades de la diversitat geogràfica") %>%
  kable_styling(latex_options = c("striped", "condensed", "scale_down", "HOLD_position"), 
                position = "center", full_width = FALSE)


```






```{r}

library(readxl)

data3 <- read_excel("data3.xlsx")

variables3 <- names(data3)
clase3 <- c("Character", "Numeric", "Character", "Character", "Character", "Character", 
            "Character", "Character","Character", "Character")
categories3 <- c("AAIC / ADPD / CEB / ESHGC / IBC / ISFTD / JBG / MICCAI / OHBMC", 
                "2012 / 2013 / 2014 / 2015 / 2016 / 2017 / 2018 / 2019 / 2020 / 2021 / 2022 / 2023", 
                "No categories", "W (dona) / M (home)", "No categories", "No categories",
                "Àfrica / Amèrica del Nord / Amèrica del Sud / Àsia / Europa / Oceania" , 
                 "Internacional / Nacional", "Biomedicina / Bioestadística", "Sí / No")


x <- cbind(variables3, clase3, categories3)

x %>%
  kable(booktabs = TRUE, format = "latex", col.names = c("Variables", "Classe", "Categories"), 
        caption = "Variables de la base de dades general") %>%
  kable_styling(latex_options = c("striped", "condensed", "scale_down", "HOLD_position"), 
                position = "center", full_width = FALSE)

```







```{r}
data$Conferència <- as.factor(data$Conferència)
data$Any <- as.factor(data$Any)
data$TipusConferència <- as.factor(data$TipusConferència)
data$Temàtica <- as.factor(data$Temàtica)
data$Covid <- as.factor(data$Covid)


data2$Conferencia <- as.factor(data2$Conferencia)
data2$Any <- as.factor(data2$Any)
data2$Continent <- as.factor(data2$Continent)
data2$TipusConferència <- as.factor(data2$TipusConferència)
data2$Temàtica <- as.factor(data2$Temàtica)
data2$Covid <- as.factor(data2$Covid)


data3$Conferència <- as.factor(data3$Conferència)
data3$Any <- as.factor(data3$Any)
data3$Gènere <- as.factor(data3$Gènere)
data3$Continent <- as.factor(data3$Continent)
data3$TipusConferència <- as.factor(data3$TipusConferència)
data3$Temàtica <- as.factor(data3$Temàtica)
data3$Covid <- as.factor(data3$Covid)


```





```{r}
confestotals <- data.frame(Confe = c("AAIC", "ADPD", "CEB", "ESHGC", "OHBMC", "IBC", "ISFTD", 
                                     "JBG", "MICCAI"),
                           NumConfe = c(6, 5, 5, 5, 6, 5, 3, 6, 5))


library(ggplot2)
library(dplyr)

hsize <- 3

confestotals <- confestotals %>% 
  mutate(x = hsize)

ggplot(confestotals, aes(x = hsize, y = NumConfe, fill = Confe)) +
  geom_col(color = "black") +
  geom_text(aes(label = NumConfe),
             position = position_stack(vjust = 0.5)) +
  coord_polar(theta = "y") +
  scale_fill_brewer(palette = "Set3") +
  xlim(c(0.2, hsize + 0.5)) +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank()) +
  labs(title = "Número d'anys analitzats de cada conferència")
 
 




ggplot(data = data) +
  geom_point(aes(x = Any, y = Conferència, color = Conferència, size = 3)) +
  scale_colour_brewer(palette = "Set3") +
  theme_minimal() + 
  labs(title = "Conferències per any analitzades", x = "Anys", y = "Conferències") 
 
  
  
ggplot(data = data) +
  geom_point(aes(x = Temàtica, y = Conferència, color = Conferència, size = 3)) +
  scale_colour_brewer(palette = "Set3") +
  theme_minimal() + 
  labs(title = "Conferències per any analitzades", x = "Anys", y = "Conferències") 
 


```















```{r}

variables_num <- c("Total Convidats", "Total Dones","Total Homes")
mitjana <- c(round(mean(data$TotalConvidats, na.rm = T), 2), 
             round(mean(data$TotalDones, na.rm = T), 2), 
             round(mean(data$TotalHomes, na.rm = T), 2))
sd <- c(round(sd(data$TotalConvidats, na.rm = T), 2), 
        round(sd(data$TotalDones, na.rm = T), 2), 
        round(sd(data$TotalHomes, na.rm = T), 2))

x_1 <- cbind(variables_num, mitjana, sd)

x_1 %>%
  kable(booktabs = TRUE, format = "latex", col.names = c("Variables numèriques", "Mitjana", "Desviació típica"),
        caption = "Resum de les variables numèriques") %>%
  kable_styling(latex_options = c("striped"), 
                position = "center", full_width = FALSE)
```






```{r}

total <- nrow(data3)
Afri <- round((sum(data3$Continent == "Àfrica") / total) * 100, 1)
AN <- round((sum(data3$Continent == "Amèrica del Nord") / total) * 100, 1)
AS <- round((sum(data3$Continent == "Amèrica del Sud") / total) * 100, 1)
A <- round((sum(data3$Continent == "Àsia") / total) * 100, 1)
E <- round((sum(data3$Continent == "Europa") / total) * 100, 1)
O <- round((sum(data3$Continent == "Oceania") / total) * 100, 1)

datageo <- data.frame(
  Continents = c("Àfrica", "Amèrica del Nord", "Amèrica del Sud", "Àsia", "Europa", "Oceania"), 
  Percentatge = c(Afri, AN, AS, A, E, O))

ggplot(datageo, aes(x = Continents, y = Percentatge, fill = Continents)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(aes(label = paste(Percentatge, "%")), vjust = -.5, size = 3, colour = "black") +
  theme_minimal() +
  ylim(0, 100) +
  scale_fill_brewer(palette = "Set3") +
  labs(title = "Percentatge de ponents per continent") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5))
  


```





```{r}
ggplot(data, aes(x = Any, y = Covid, color = Covid, size = 3)) +
  geom_point() +
  scale_colour_brewer(palette = "Set3") +
  theme_minimal() +
  labs(x = "Anys", y = "Covid", title = "Relació entre els anys i la Covid") + 
  scale_x_continuous(breaks = data$Any, minor_breaks = NULL)


  
ggplot(data = data) +
  geom_point(aes(x = Temàtica, y = Conferència, color = Conferència, size = 3)) +
  scale_colour_brewer(palette = "Set3") +
  theme_minimal() + 
  labs(title = "Conferències per any analitzades", x = "Anys", y = "Conferències") 
 
```




















## Percentage de dones ponents convidades en les diferents conferències

```{r, warning=FALSE}


PercentatgeDones <- round((data$TotalDones / data$TotalConvidats) * 100, 0)
data <- cbind(data, PercentatgeDones)




library(ggplot2)

ggplot(data = data, 
                  aes(x = Any, y = PercentatgeDones, group = Conferència, na.rm = TRUE)) +
  geom_line(aes(color = Conferència)) + 
  geom_point(aes(color = Conferència)) +  
  ylim(0, 100) +
  theme_minimal() +
  scale_x_continuous(breaks = data$Any, minor_breaks = NULL) +
  labs(title = "Percentage de dones ponents convidades en les diferents conferències", 
       x = "Anys", y = "Percentatge de dones")



ggplot(data = data, aes(x = Any, y = PercentatgeDones, group = Conferència, na.rm = TRUE)) + 
  geom_line(aes(color = Conferència)) + 
  geom_point(aes(color = Conferència)) + 
  facet_wrap(~Conferència) + 
  theme_minimal() +
  ylim(0, 100) +
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1)) +
  scale_x_continuous(breaks = data$Any, minor_breaks = NULL) +
  labs(title = "Percentage de dones ponents convidades en les diferents conferències", x = "Anys", y = "Percentatge de dones")



```







## Percentage de dones ponents convidades per tipus de conferència
```{r}
Dones_Nac_Internac <- aggregate(cbind(TotalDones, TotalConvidats) ~ TipusConferència, data = data, sum)
PercentatgeDones_Nac_Internac <- round((Dones_Nac_Internac$TotalDones / Dones_Nac_Internac$TotalConvidats) * 100, 1)
Dones_Nac_Internac <- cbind(Dones_Nac_Internac, PercentatgeDones_Nac_Internac)


ggplot(Dones_Nac_Internac, aes(x = TipusConferència, y = PercentatgeDones_Nac_Internac, 
                               fill = TipusConferència)) + 
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(aes(label = paste(round(PercentatgeDones_Nac_Internac, 1), "%")), vjust = -0.5, colour = "black") +
  theme_minimal() +
  ylim(0, 100) +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Tipus de conferència", y = "Percentage de dones", 
       title = "Percentage de dones ponents convidades per tipus de conferencia")


```







## Percentage de dones ponents convidades per tipus de temàtica
```{r}
Dones_Med_Est <- aggregate(cbind(TotalDones, TotalConvidats) ~ Temàtica, data = data, sum)
PercentatgeDones_Med_Est <- round((Dones_Med_Est$TotalDones / Dones_Med_Est$TotalConvidats) * 100, 1)
Dones_Med_Est <- cbind(Dones_Med_Est, PercentatgeDones_Med_Est)


ggplot(Dones_Med_Est, aes(x = Temàtica, y = PercentatgeDones_Med_Est,
                          fill = Temàtica)) + 
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(aes(label = paste(round(PercentatgeDones_Med_Est, 1), "%")), vjust = -0.5, colour = "black") +
  theme_minimal() +
  ylim(0, 100) +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Tipus de temàtica", y = "Percentage de dones", 
       title = "Percentage de dones ponents convidades per tipus de temàtica") 


```










```{r}
AAIC <- data2[1:36,]
ADPD <- data2[37:72,]
CEB <- data2[73:108,]
ESHGC <- data2[109:144,]
OHBMC <- data2[145:180,]
IBC <- data2[181:216,]
ISFTD <- data2[217:252,]
JBG <- data2[253:288,]
MICCAI <- data2[289:324,]

require(dplyr)
# general
data2 <- data2 %>%
  group_by(Any, Continent) %>%
  summarise(Ponents = sum(Ponents)) %>%
  group_by(Any) %>%
  mutate(porcentaje = (Ponents / sum(Ponents)) * 100)


data2$porcentaje <- round(data2$porcentaje, 1)

ggplot(data2, aes(x = factor(Any), y = porcentaje, fill = Continent)) +
  geom_bar(stat = "identity") +
  geom_text(data = subset(data2, porcentaje != 0), aes(label = paste0(porcentaje, "%")), 
            position = position_stack(vjust = .5), size = 3, color = "black") +
  theme_minimal() +
  facet_wrap(~Conferència) + 
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Any", y = "Percentatge", title = "Diversitat geogràfica dels ponents convidats", fill = "Continent") +
  theme(legend.position = "right")





```




```{r}
# AAIC
AAIC <- AAIC %>%
  group_by(Any, Continent) %>%
  summarise(Ponents = sum(Ponents)) %>%
  group_by(Any) %>%
  mutate(porcentaje = (Ponents / sum(Ponents)) * 100)

AAIC$porcentaje <- round(AAIC$porcentaje, 1)

ggplot(AAIC, aes(x = factor(Any), y = porcentaje, fill = Continent)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(data = subset(AAIC, porcentaje != 0), aes(label = paste0(porcentaje, "%")), 
            position = position_stack(vjust = .5), size = 3, color = "black") +
   theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Any", y = "Percentatge", title = "Diversitat geogràfica dels ponents convidats a AAIC", fill = "Continent") +
  theme(legend.position = "right")
```





```{r}

# ADPD
ADPD <- ADPD %>%
  group_by(Any, Continent) %>%
  summarise(Ponents = sum(Ponents)) %>%
  group_by(Any) %>%
  mutate(porcentaje = (Ponents / sum(Ponents)) * 100)

ADPD$porcentaje <- round(ADPD$porcentaje, 1)

ggplot(ADPD, aes(x = factor(Any), y = porcentaje, fill = Continent)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(data = subset(ADPD, porcentaje != 0), aes(label = paste0(porcentaje, "%")), 
            position = position_stack(vjust = .5), size = 3, color = "black") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Any", y = "Percentatge", title = "Diversitat geogràfica dels ponents convidats a ADPD", fill = "Continent") +
  theme(legend.position = "right")
```







```{r}

# CEB
CEB <- CEB %>%
  group_by(Any, Continent) %>%
  summarise(Ponents = sum(Ponents)) %>%
  group_by(Any) %>%
  mutate(porcentaje = (Ponents / sum(Ponents)) * 100)

CEB$porcentaje <- round(CEB$porcentaje, 1)

ggplot(CEB, aes(x = factor(Any), y = porcentaje, fill = Continent)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(data = subset(CEB, porcentaje != 0), aes(label = paste0(porcentaje, "%")), 
            position = position_stack(vjust = .5), size = 3, color = "black") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Any", y = "Percentatge", title = "Diversitat geogràfica dels ponents convidats a CEB", fill = "Continent") +
  theme(legend.position = "right")
```






```{r}
# ESHGC
ESHGC <- ESHGC %>%
  group_by(Any, Continent) %>%
  summarise(Ponents = sum(Ponents)) %>%
  group_by(Any) %>%
  mutate(porcentaje = (Ponents / sum(Ponents)) * 100)

ESHGC$porcentaje <- round(ESHGC$porcentaje, 1)

ggplot(ESHGC, aes(x = factor(Any), y = porcentaje, fill = Continent)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(data = subset(ESHGC, porcentaje != 0), aes(label = paste0(porcentaje, "%")), 
            position = position_stack(vjust = .5), size = 3, color = "black") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Any", y = "Percentatge", title = "Diversitat geogràfica dels ponents convidats a ESHGC", fill = "Continent") +
  theme(legend.position = "right")

```







```{r}
# OHBMC
OHBMC <- OHBMC %>%
  group_by(Any, Continent) %>%
  summarise(Ponents = sum(Ponents)) %>%
  group_by(Any) %>%
  mutate(porcentaje = (Ponents / sum(Ponents)) * 100)

OHBMC$porcentaje <- round(OHBMC$porcentaje, 1)

ggplot(OHBMC, aes(x = factor(Any), y = porcentaje, fill = Continent)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(data = subset(OHBMC, porcentaje != 0), aes(label = paste0(porcentaje, "%")), 
            position = position_stack(vjust = .5), size = 3, color = "black") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Any", y = "Percentatge", title = "Diversitat geogràfica dels ponents convidats a OHBMC", fill = "Continent") +
  theme(legend.position = "right")

```





```{r}
# IBC
IBC <- IBC %>%
  group_by(Any, Continent) %>%
  summarise(Ponents = sum(Ponents)) %>%
  group_by(Any) %>%
  mutate(porcentaje = (Ponents / sum(Ponents)) * 100)

IBC$porcentaje <- round(IBC$porcentaje, 1)

ggplot(IBC, aes(x = factor(Any), y = porcentaje, fill = Continent)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(data = subset(IBC, porcentaje != 0), aes(label = paste0(porcentaje, "%")), 
            position = position_stack(vjust = .5), size = 3.5, color = "black") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Any", y = "Percentatge", title = "Diversitat geogràfica dels ponents convidats a IBC", fill = "Continent") +
  theme(legend.position = "right")
```










```{r}

# ISFTD
ISFTD <- ISFTD %>%
  group_by(Any, Continent) %>%
  summarise(Ponents = sum(Ponents)) %>%
  group_by(Any) %>%
  mutate(porcentaje = (Ponents / sum(Ponents)) * 100)

ISFTD$porcentaje <- round(ISFTD$porcentaje, 1)

ggplot(ISFTD, aes(x = factor(Any), y = porcentaje, fill = Continent)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(data = subset(ISFTD, porcentaje != 0), aes(label = paste0(porcentaje, "%")), 
            position = position_stack(vjust = .5), size = 3, color = "black") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Any", y = "Percentatge", title = "Diversitat geogràfica dels ponents convidats a ISFTD", fill = "Continent") +
  theme(legend.position = "right")

```








```{r}
# JBG
JBG <- JBG %>%
  group_by(Any, Continent) %>%
  summarise(Ponents = sum(Ponents)) %>%
  group_by(Any) %>%
  mutate(porcentaje = (Ponents / sum(Ponents)) * 100)

JBG$porcentaje <- round(JBG$porcentaje, 1)

ggplot(JBG, aes(x = factor(Any), y = porcentaje, fill = Continent)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(data = subset(JBG, porcentaje != 0), aes(label = paste0(porcentaje, "%")), 
            position = position_stack(vjust = .5), size = 3, color = "black") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Any", y = "Percentatge", title = "Diversitat geogràfica dels ponents convidats a £JBG", fill = "Continent") +
  theme(legend.position = "right")

```





```{r}

# MICCAI
MICCAI <- MICCAI %>%
  group_by(Any, Continent) %>%
  summarise(Ponents = sum(Ponents)) %>%
  group_by(Any) %>%
  mutate(porcentaje = (Ponents / sum(Ponents)) * 100)

MICCAI$porcentaje <- round(MICCAI$porcentaje, 1)

ggplot(MICCAI, aes(x = factor(Any), y = porcentaje, fill = Continent)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(data = subset(MICCAI, porcentaje != 0), aes(label = paste0(porcentaje, "%")), 
            position = position_stack(vjust = .5), size = 3, color = "black") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Any", y = "Percentatge", title = "Diversitat geogràfica dels ponents convidats a MICCAI", fill = "Continent") +
  theme(legend.position = "right")

```





```{r}
# CONFERENCIES NACIONALS

data2 <- read_excel("data2.xlsx")

CEB <- data2[73:108,]
JBG <- data2[253:288,]

confe_nac <- rbind(CEB, JBG)

confe_nac <- confe_nac %>%
  group_by(Continent) %>%
  summarise(Ponents = sum(Ponents)) %>%
  mutate(porcentaje = (Ponents / sum(Ponents)) * 100)

confe_nac$porcentaje <- round(confe_nac$porcentaje, 1)

ggplot(confe_nac, aes(x = Continent, y = porcentaje, fill = Continent)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(data = confe_nac, aes(label = paste0(porcentaje, "%")), size = 3, hjust = -.3) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Continents", y = "Percentatge", title = "Diversitat geogràfica dels ponents convidats a conferències nacionals", fill = "Continent") +
  theme(legend.position = "right") +
  scale_y_continuous(limits = c(0, 100), expand = c(0, 0)) +
  coord_flip()

```







```{r}


# CONFERENCIES INTERNACIONALS

AAIC <- data2[1:36,]
ADPD <- data2[37:72,]
ESHGC <- data2[109:144,]
OHBMC <- data2[145:180,]
IBC <- data2[181:216,]
ISFTD <- data2[217:252,]
MICCAI <- data2[289:324,]

confe_internac <- rbind(AAIC, ADPD, ESHGC, OHBMC, IBC, ISFTD, MICCAI)

confe_internac <- confe_internac %>%
  group_by(Continent) %>%
  summarise(Ponents = sum(Ponents)) %>%
  mutate(porcentaje = (Ponents / sum(Ponents)) * 100)

confe_internac$porcentaje <- round(confe_internac$porcentaje, 1)

ggplot(confe_internac, aes(x = Continent, y = porcentaje, fill = Continent)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(data = confe_internac, aes(label = paste0(porcentaje, "%")), size = 3, hjust = -.3) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Continents", y = "Percentatge", title = "Diversitat geogràfica dels ponents convidats a conferències internacionals", fill = "Continent") +
  theme(legend.position = "right") +
  scale_y_continuous(limits = c(0, 100), expand = c(0, 0)) +
  coord_flip()


```







```{r}
# CONFERENCIES BIOESTADISTICA

CEB <- data2[73:108,]
IBC <- data2[181:216,]


confe_bioest <- rbind(CEB, IBC)

confe_bioest <- confe_bioest %>%
  group_by(Continent) %>%
  summarise(Ponents = sum(Ponents)) %>%
  mutate(porcentaje = (Ponents / sum(Ponents)) * 100)

confe_bioest$porcentaje <- round(confe_bioest$porcentaje, 1)

ggplot(confe_bioest, aes(x = Continent, y = porcentaje, fill = Continent)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(data = confe_bioest, aes(label = paste0(porcentaje, "%")), size = 3, hjust = -.3) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Continents", y = "Percentatge", title = "Diversitat geogràfica dels ponents a conferències de bioestadística", fill = "Continent") +
  theme(legend.position = "right") +
  scale_y_continuous(limits = c(0, 100), expand = c(0, 0)) +
  coord_flip()


```







```{r}


# CONFERENCIES BIOMEDICINA

AAIC <- data2[1:36,]
ADPD <- data2[37:72,]
ESHGC <- data2[109:144,]
OHBMC <- data2[145:180,]
ISFTD <- data2[217:252,]
MICCAI <- data2[289:324,]
JBG <- data2[253:288,]

confe_biomed <- rbind(AAIC, ADPD, ESHGC, OHBMC, ISFTD, MICCAI, JBG)

confe_biomed <- confe_biomed %>%
  group_by(Continent) %>%
  summarise(Ponents = sum(Ponents)) %>%
  mutate(porcentaje = (Ponents / sum(Ponents)) * 100)

confe_biomed$porcentaje <- round(confe_biomed$porcentaje, 1)

ggplot(confe_biomed, aes(x = Continent, y = porcentaje, fill = Continent)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  geom_text(data = confe_biomed, aes(label = paste0(porcentaje, "%")), size = 3, hjust = -.3) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Continents", y = "Percentatge", title = "Diversitat geogràfica dels ponents a conferències de biomedicina", fill = "Continent") +
  theme(legend.position = "right") +
  scale_y_continuous(limits = c(0, 100), expand = c(0, 0)) +
  coord_flip()

```
























# INFERENCIA


# Test de Fisher fallido
```{r}

dat <- data.frame(
  "H" = c(4, 2, 0, 2, 41, 0, 53, 28, 20, 55, 77, 16),
  "M" = c(1, 1, 0, 1, 20, 0, 37, 19, 18, 49, 56, 17),
  row.names = c("2012", "2013", "2014", "2015", "2016", "2017", 
                "2018", "2019", "2020", "2021", "2022", "2023"),
  stringsAsFactors = FALSE)

dat <- data.frame(
  "H" = c(77, 16),
  "M" = c(56, 17),
  row.names = c("2022", "2023"),
  stringsAsFactors = FALSE)

colnames(dat) <- c("Home", "Dona")

mosaicplot(dat,
  main = "Mosaic plot",
  color = TRUE
)

chisq.test(dat)$expected


test <- fisher.test(dat)
test

```






# modelo lineal Q1
```{r}
dones <- c(1, 1, 0, 1, 20, 0, 37, 19, 18, 49, 56, 17)
homes <- c(4, 2, 0, 2, 41, 0, 53, 28, 20, 55, 77, 16)
any <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)

datanat <- data.frame(AnyConfe = any, 
                      Dones = dones, 
                      Homes = homes)

fit <- lm(Dones ~ AnyConfe, data = datanat)

summary(fit)







dones <- c(37, 19, 18, 49, 56, 17)
homes <- c(53, 28, 20, 55, 77, 16)
any <- c(1, 2, 3, 4, 5, 6)

datanat <- data.frame(AnyConfe = any, 
                      Dones = dones, 
                      Homes = homes)

fit <- lm(Dones ~ AnyConfe, data = datanat)

summary(fit)
```





# anova Q1
```{r}
anovares <- aov(Dones + Homes ~ AnyConfe, data=datanat)
summary(anovares)

TukeyHSD(anovares)


Ponents <- c(rep(1, nrow(data3)))
data3 <- cbind(data3, Ponents)

anova_result <- aov(Ponents ~ Gènere, data = data3)
summary(anova_result)

```




















# modelo lineal Q2
```{r}
sum(data3$Continent == "Àfrica" & data3$Any == 2018) 
sum(data3$Continent == "Amèrica del Nord" & data3$Any == 2023)
sum(data3$Continent == "Amèrica del Sud" & data3$Any == 2023)
sum(data3$Continent == "Àsia" & data3$Any == 2023)
sum(data3$Continent == "Europa" & data3$Any == 2023)
sum(data3$Continent == "Oceania" & data3$Any == 2023)

ponAfri <- c(0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0)
ponAN <- c(1, 1, 0, 1, 30, 0, 29, 18, 17, 50, 56, 16)
ponAS <- c(0, 0, 0, 0, 2, 0, 1, 0, 0, 14, 3, 1)
ponA <- c(3, 0, 0, 0, 4, 0, 6, 7, 2, 7, 8, 5)
ponE <- c(1, 2, 0, 2, 22, 0, 40, 21, 16, 30, 60, 11)
ponO <- c(0, 0, 0, 0, 3, 0, 13, 1, 3, 6, 6, 0)

any <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)

datanat <- data.frame(AnyConfe = any,
                      PonentsAfri = ponAfri, 
                      PonentsAN = ponAN, 
                      PonentsAS = ponAS, 
                      PonentsA = ponA,
                      PonentsE = ponE,
                      PonentsO = ponO)

fitAfri <- lm(PonentsAfri ~ AnyConfe, data = datanat)
fitAN <- lm(PonentsAN ~ AnyConfe, data = datanat)
fitAS <- lm(PonentsAS ~ AnyConfe, data = datanat)
fitA <- lm(PonentsA ~ AnyConfe, data = datanat)
fitE <- lm(PonentsE ~ AnyConfe, data = datanat)
fitO <- lm(PonentsO ~ AnyConfe, data = datanat)

summary(fitAfri)
summary(fitAN)
summary(fitAS)
summary(fitA)
summary(fitE)
summary(fitO)



```












# anova Q2
```{r}

anovares <- aov(PonentsAfri + PonentsAN + PonentsAS + PonentsA + PonentsE + PonentsO ~ AnyConfe, data=datanat)
summary(anovares)



# Realizar el análisis de varianza (ANOVA)
anova_result <- aov(Ponents ~ Continent, data = data2)


# Mostrar los resultados
print(summary(anova_result))

TukeyHSD(anova_result)




```








